// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sim_Web.Db;

#nullable disable

namespace Sim_Web.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230406203041_New3")]
    partial class New3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.15");

            modelBuilder.Entity("Sim_Web.Models.LoginData", b =>
                {
                    b.Property<string>("usr")
                        .HasColumnType("TEXT");

                    b.Property<string>("pw")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("usr");

                    b.ToTable("loginDatas");
                });

            modelBuilder.Entity("Sim_Web.Models.SimulationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllDeadPeoples")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllHealthyPeoples")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllInfectedPeoples")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AllPeople")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SimulationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("simulationDatas");
                });

            modelBuilder.Entity("Sim_Web.Models.SimulationRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateOfRun")
                        .HasColumnType("TEXT");

                    b.Property<string>("RectanglePointers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RectanglesWithPeople")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VirusName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("simulationRuns");
                });

            modelBuilder.Entity("Sim_Web.Models.Virus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("IncubationTime")
                        .HasColumnType("REAL");

                    b.Property<double>("InfectionSeverity")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ProbabilityToCure")
                        .HasColumnType("REAL");

                    b.Property<double>("ProbabilityToDead")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("VirusData");
                });
#pragma warning restore 612, 618
        }
    }
}
